name := "CEFparser"
version := "1.0"
scalaVersion := "2.11.8"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4"
libraryDependencies += "com.typesafe" % "config" % "1.3.0"